### PR TITLE
chore(tests): add tests for proxysettings custom resource

### PR DESCRIPTION
**Pull request by arriqaaq**
Adds tests for https://github.com/clastix/capsule-proxy/issues/197

### CODE REVIEW

**Comment by arriqaaq** [comment]
@prometherion @MaxFedotov Should I replicate the proxysetting CR creation process for the other tests (like namespaces, nodes, priority classes, storage classes etc)? Since there is also support for owners through the tenant spec itself, and I assume we'd like to keep both type of tests (adding perms through tenant spec or through proxysetting CR), what are your thoughts?

**Comment by prometherion** [comment]
I don't think we need to create so many cases, also considering #193, BATS is cool but actually, we're ending up with too many duplications of code.

Regarding the test case, since the feature is addressed as a middleware in the function `getTenantsForOwner`, there's no need to test the `ProxySetting` for each supported kind.

**Review by prometherion — APPROVED** [review]

**Comment by prometherion** [comment]
Thanks a lot, @arriqaaq, going to merge tests on the base feature branch and fix CI to see the result of the changes! 👀

**Comment by arriqaaq** [comment]
Thank you @prometherion , loved reading the code

**Pull request merged**
