### PR TITLE
docs(minor): pointing documentation to capsule one

### LINKED ISSUE #179: Move the docs to the main Capsule repo
Currently, the documentation about Capsule and its ecosystem is included into `/docs` folder of the main Capsule repository. This repo provides the content for the [Capsule documentation](https://capsule.clastix.io) website, including the `capsule-proxy`.  Having two different places where store documentation is not a good idea since it can lead to duplications, error and misalignments.

Proposal here is to leave in the `capsule-proxy` repo just a basic README about the goal of the project and put a link to the general Capsule documentation website.

### PR DESCRIPTION
**Pull request by prometherion**
Closes #179.

In the meantime, working on Capsule side to align to current `capsule-proxy` changes.

### CODE REVIEW

**Review by bsctl — COMMENTED** [review]
Contributing guidelines for proxy are already in capsule.clastix.io . Do we need for it here too?

**Comment by prometherion** [comment]
Honestly, I would refactor the contribution guidelines such as setting up a local development environment per extension rather than in the Operator one since these could differ.

**Comment by bsctl** [comment]
so we’ve to clean what is now in capsule doc?

**Comment by prometherion** [comment]
I'm working on that! 💯

**Pull request merged**
