### PR TITLE
fix: update golang to 1.19

### PR DESCRIPTION
**Pull request by slimm609**
update golang to 1.19 to allow for easier recompile using boringcrypto added to main in 1.19. Also moved from alpine to just regular golang to standardize between capsule and capsule-proxy.

### CODE REVIEW

**Comment by prometherion** [comment]
LGTM @slimm609 but I wouldn't define this as a fix, rather, `deps` as a semantic commit subject.

The GH changes could be marked as `chore(github)`.

Once amended commit messages, ready to get it merged.

**Comment by slimm609** [comment]
rebased and amended into multiple

**Comment by slimm609** [comment]
@prometherion this should be good now

**Review by prometherion — APPROVED** [review]
Thanks, @slimm609!

**Pull request merged**
