### PR TITLE
Tenant v1beta2 support

### LINKED ISSUE #246: Align with capsule v0.2.0 release
# Describe the feature

Align used API Versions with new versions from https://github.com/clastix/capsule/milestone/4. Make sure we release a new version of capsule proxy with allows a smooth migration to capsule 0.2.0 including migrating capsule-proxy.

Identified following changes:

- https://github.com/clastix/capsule-proxy/blob/master/main.go#L38: Add `capsulev1beta2` to scheme
-  https://github.com/clastix/capsule-proxy/blob/master/internal/controllers/capsule_configuration.go#L9: must be bumped to   `capsulev1beta2`
- https://github.com/clastix/capsule-proxy/blob/master/internal/controllers/role_bindings.go#L12: must be bumped to   `capsulev1beta2`

Test changes with main branch of capsule and verify everything is working as expected.

### PR DESCRIPTION
**Pull request by oliverbaehler**
Closes #246 

Bumps capsule to 0.2.0 and implements v1beta2. Will require a new major version as well. I would suggest releasing with the currently open features:

 * #249 
 * #245 

The feature for the selectors is only currently implemented for PriorityClasses. Before I continue I would like your feedback @prometherion. It would probably be better regarding performance to have the selector already preavaluated, than looping through all the available selectors here:

https://github.com/clastix/capsule-proxy/blob/issue/246/internal/modules/priorityclass/utils.go#L87

However I haven't found a way to do it. I noticed there's a `labels.Merge()` func, but this doesn't help. Maybe you have a smart way to return one selector object, which consists of all the proxyTenants selectors:

https://github.com/clastix/capsule-proxy/blob/issue/246/internal/modules/priorityclass/utils.go#L21

### CODE REVIEW

**Comment by prometherion** [comment]
I think we should change the signature of `getPriorityClassSelector` in order to return a set of `*labels.Requirement` that will be used to create the Selector here:

https://github.com/clastix/capsule-proxy/blob/04006c61c5bc1a0e391eb151ec9eec46773abc5f/internal/modules/priorityclass/list.go#L61

I'll try to work on a bit on your changes.

**Comment by prometherion** [comment]
@oliverbaehler take a look [here](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#resources-that-support-set-based-requirements)

> Caution: For both equality-based and set-based conditions there is no logical OR (||) operator. Ensure your filter statements are structured accordingly.

With that said, we need to make `capsule-proxy` a bit hacky, I'd say: `matchLabels` and `matchRequirements` will have preference over the `regex` and `name`, also considering we plan to deprecate the latter ones since not properly aligned to the set-base selection philosophy in Kubernetes.

WDYT?

**Comment by oliverbaehler** [comment]
@prometherion annoying that OR is not supported. We are facing the same dilemma with the Default tenant value. I guess would only be solvable with something like #57

**Comment by prometherion** [comment]
Table generation is unfeasible, at least in the short term.

Let's go for prioritizing the matchLabels/matchRequirements over the exact/regex matches, also considering that the latter ones will be deprecated in future by Capsule.

**Comment by oliverbaehler** [comment]
@prometherion What about the default? should we just not support it for now?

**Comment by prometherion** [comment]
We have to inform end-users that even the default must match the matchLabels/matchRequirements, although not required in Capsule, just for listing purposes.

**Comment by prometherion** [comment]
Closes #266 too with commit 34eba3b.

**Pull request merged**
