### PR TITLE
Support for user impersonation

### LINKED ISSUE #215: Add support for impersonated requests
This issue tracks the proposal to also support impersonated requests.

## Background

As Capsule Proxy proxies requests to the Kubernetes API server, it uses its own identity to impersonate the identity of the incoming request, towards the API server.

As of now, if the incoming request is in turn trying to impersonate a user (and possibly groups, as for `Impersonate-User` + `Impersonate-Groups` HTTP header values), the impersonation headers are ignored and overridden by Capsule Proxy with the identity of the incoming request.

## The feature

As such, Capsule Proxy would proxy requests to the API server impersonating on behalf of the identity of the incoming request, the user and the groups that that identity is trying to impersonate, if and only if, the token of that identity has required permissions bound.

## Use cases

An example use case is the one from [capsule #528](https://github.com/clastix/capsule/issues/528).

### PR DESCRIPTION
**Pull request by prometherion**
Closes #215.

### CODE REVIEW

**Comment by maxgio92** [comment]
What do you think @prometherion about returning 403 when failing getting user and groups because of missing privilege to impersonate that user/groups?

Something like [this](https://github.com/clastix/capsule-proxy/compare/issues/215...issues/215-unauthorized).

**Comment by prometherion** [comment]
Totally agree, could you open PR with these proposed changes?

**Comment by maxgio92** [comment]
Done in #217

**Comment by maxgio92** [comment]
I'm encountering this:

```
$ kubectl --as foo get pods
...
I0617 12:27:00.063085 1251857 round_trippers.go:466] curl -v -XGET  -H "User-Agent: kubectl/v1.24.1 (linux/amd64) kubernetes/3ddd0f4" -H "Accept: application/json, */*" -H "Impersonate-User: foo" -H "Authorization: Bearer <masked>" 'https://capsule-proxy:9001/api?timeout=32s'
I0617 12:27:00.065436 1251857 round_trippers.go:553] GET https://capsule-proxy:9001/api?timeout=32s 200 OK in 2 milliseconds
I0617 12:27:00.065469 1251857 round_trippers.go:570] HTTP Statistics: GetConnection 0 ms ServerProcessing 2 ms Duration 2 ms
I0617 12:27:00.065479 1251857 round_trippers.go:577] Response Headers:
I0617 12:27:00.065490 1251857 round_trippers.go:580]     Date: Fri, 17 Jun 2022 10:27:00 GMT
I0617 12:27:00.065499 1251857 round_trippers.go:580]     Content-Type: application/json
I0617 12:27:00.065507 1251857 round_trippers.go:580]     Content-Length: 218
I0617 12:27:00.075562 1251857 request.go:1073] Response Body: {"kind":"Status","apiVersion":"v1","metadata":{},"message":"cannot retrieve user and group: the current user system:serviceaccount:dev-team:gitops-reconciler cannot impersonate the user foo","reason":"InternalError"}
I0617 12:27:00.084284 1251857 cached_discovery.go:119] skipped caching discovery info due to converting (v1.Status) to (v1.APIVersions): unknown conversion
error: converting (v1.Status) to (v1.APIVersions): unknown conversion
```

Going to debug it.

**Comment by maxgio92** [comment]
The issue is that with this implementation `kubeFilter.allowedPaths` are blocked for inability to set user/groups from impersonation headers, if the user does not have the permissions.
In example the discovery clients ask for `/api` resource:

```
$ curl -s -k -XGET  \
  -H "Accept: application/json, */*" \
  -H "Impersonate-User: admin" \
  -H "Authorization: Bearer ${TOKEN}" \
  -H "User-Agent: kubectl/v1.24.1 (linux/amd64) kubernetes/3ddd0f4" "${CAPSULEPROXY}/api"
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "cannot retrieve user and group: the current user system:serviceaccount:dev-team:gitops-reconciler cannot impersonate the user admin",
  "reason": "InternalError",
  "details": {
    "name": "admin",
    "kind": "users"
  },
  "code": 500
}
```

**Comment by maxgio92** [comment]
I added a couple of lintings @prometherion. Last two commtis. Could you give a check on that?

Besides that, I think is ready to be merged.

**Comment by maxgio92** [comment]
Done, thanks @prometherion

**Review by maxgio92 — APPROVED** [review]
LGTM

**Pull request merged**
