### PR TITLE
Read and Update on Node resource

### LINKED ISSUE #40: Access the node details
The #38 introduce support for nodes filtering. With this PR only nodes listing is permitted.

```
$ kubectl get nodes 
NAME                STATUS   ROLES    AGE   VERSION
k8s-caas-worker01   Ready    worker   96d   v1.19.1
k8s-caas-worker02   Ready    worker   96d   v1.19.1
k8s-caas-worker03   Ready    worker   96d   v1.19.1
k8s-caas-worker04   Ready    worker   96d   v1.19.1
k8s-caas-worker05   Ready    worker   96d   v1.19.1
k8s-caas-worker06   Ready    worker   96d   v1.19.1

$ kubectl get node k8s-caas-worker01
Error from server (Forbidden): nodes "k8s-caas-worker01" is forbidden: User "alice" cannot get resource "nodes" in API group "" at the cluster scope
```
This is correct according to the initial feature request #21. It makes sense to give also the details of each node item for inspecting its status and monitoring.  I'm opening this feature request according to this [comment](https://github.com/clastix/capsule-ns-filter/pull/38#issuecomment-749169204)

### PR DESCRIPTION
**Pull request by prometherion**
Closes #40 and allows to retrieve the single Node as well labeling it.

### CODE REVIEW

**Comment by prometherion** [comment]
Well, I guess I went too much with this.

It's ok getting the single resource, but should we also allow any operation against it?

What about adding these additional annotations?

- `capsule.clastix.io/enable-node-listing` allows node listing (already in place)
- `capsule.clastix.io/enable-node-update` allows PATCH and PUT requests (updates)
- `capsule.clastix.io/enable-node-deletion` allows DELETE requests (deletions)

Because with the current implementation a Tenant owner can do whatever they want, and I think giving more fine-grained control over the actions they can perform is safer: WDYT @bsctl @MaxFedotov?

**Comment by prometherion** [comment]
> What about adding these additional annotations?
> 
> * `capsule.clastix.io/enable-node-listing` allows node listing (already in place)
> * `capsule.clastix.io/enable-node-update` allows PATCH and PUT requests (updates)
> * `capsule.clastix.io/enable-node-deletion` allows DELETE requests (deletions)

Implemented with 9c877fe and testing with be67273: just keep in mind that when dealing with annotations for deletion or update, the listing one must be set to `true`, otherwise `kubectl` is not able to retrieve the single node and then perform the requested action.

**Comment by MaxFedotov** [comment]
hi @prometherion, 
thanks a lot for the great work! I think it will be a good idea to add more fine-grained control, so let's use this annotation.
btw, can you please take a look on #82? I've found a few issues when tried to run tests for your branch and fixed them in this PR.

**Comment by prometherion** [comment]
going to merge this, thanks @MaxFedotov for your help in achieving this! 🚀

**Pull request merged**
