### PR TITLE
feat: defer impersonation user assignment

### LINKED ISSUE #245: Group Impersenation Handling
# Bug description

Not sure if its considered a bug, but here's the current situation:

We are trying to implement [Teleport](https://goteleport.com/) to manage the access to our clusters. The Teleport workflow is as follows: From the terminal server the request is forwarded to a teleport agent installed on the target Kubernetes cluster. The Agent then uses the given credentials from the Terminal server and impersonates further requests with given user/groups ([Details](https://goteleport.com/docs/kubernetes-access/getting-started/#deployment-overview)). No we obviously directly want to connect to the capsule-proxy for a nice user experience for our users.  To achieve that we directed the teleport agent to the capsule-proxy endpoint :

```
extraEnv:
        - name: KUBERNETES_SERVICE_PORT_HTTPS
          value: "9001"
        - name: KUBERNETES_SERVICE_PORT
          value: "9001"
        - name: KUBERNETES_PORT_9001_TCP
          value: "tcp://capsule-proxy.capsule-system.svc:9001"
        - name: KUBERNETES_PORT_9001_TCP_PROTO
          value: "tcp"
        - name: KUBERNETES_PORT_9001_TCP_ADDR
          value: "capsule-proxy.capsule-system.svc"
        - name: KUBERNETES_SERVICE_HOST
          value: "capsule-proxy.capsule-system.svc"
        - name: KUBERNETES_PORT
          value: "tcp://capsule-proxy.capsule-system.svc:9001"
        - name: KUBERNETES_PORT_9001_TCP_PORT
          value: "443"
extraVolumeMounts:
  - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
    name: kube-api-access-capsule
    readOnly: true
extraVolumes:
  - name: kube-api-access-capsule
    projected:
      sources:
        - serviceAccountToken:
            path: token 
        - configMap:
            items:
              - key: ca.crt
                path: ca.crt
            name: capsule-root-ca.crt
        - downwardAPI:
            items:
              - fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
                path: namespace
log:
        level: DEBUG


```
(Values for [teleport agent chart](https://github.com/gravitational/teleport/blob/master/examples/chart/teleport-kube-agent/README.md))

Great. That works. But now we are getting with every request the following error:

```
cannot retrieve user and group: the current user Oliver.Baehler@bedag.ch cannot impersonate the group company-group
```

The groups are random. It doesn't work for any group. That makes sense, since the user `Oliver.Baehler@bedag.ch` is not allowed to impersonate at all.

So what's happening: 

The SA `system:serviceaccount:teleport-agent:teleport-agent` is making a request with `Impersonate-User:  Oliver.Baehler@bedag.ch`  and `Impersonate-Group: *` with all my groups. The Impersonation is [detected & accepted] (https://github.com/clastix/capsule-proxy/blob/b57445a6debb9651e2ae9d40c4ed09eb2a717ce7/internal/request/http.go#L61) because the teleport SA can impersonate as [anyone](https://github.com/gravitational/teleport/blob/master/examples/chart/teleport-kube-agent/templates/clusterrole.yaml). But now comes the Problem, since the impersonation worked, we overwrite the username to perform the next request with the value of `Impersonate-User`:

https://github.com/clastix/capsule-proxy/blob/b57445a6debb9651e2ae9d40c4ed09eb2a717ce7/internal/request/http.go#L81

So now the impersonations of groups are attempted with `Oliver.Baehler@bedag.ch`: 

https://github.com/clastix/capsule-proxy/blob/b57445a6debb9651e2ae9d40c4ed09eb2a717ce7/internal/request/http.go#L93

Since that user does not have any permission to impersonate as anyone. Every Request will fail.

Now to ask the question: Should we really overwrite the username? I guess it makes sense but it also doesn't because from a client perspective I want to define the impersonation and i don't want the impersonation be resolved via the given Impersonating User. But I guess there's other reasons to do that.

As current Workaround we tell the teleport agent to impersonate as its on serviceaccount `Impersonate-User: system:serviceaccount:teleport-agent:teleport-agent`. Then it works as expected. But since we want to create permission on tenant basis with username reference, that's not gonna be a viable solution for the future.

Let's discuss if we can change this or if there's anything else we can do to workaround this.

# How to reproduce

Given above. For detailed instructions/showcase ping me on Slack

# Expected behavior

Given `Impersonate-Group` should perform SubjectAccessReviewSpec with the user making the Request, not with the user given in `Impersonate-User`.

# Logs

Not relevant.

# Additional context

- Capsule-Proxy version:`0.3.2`

### PR DESCRIPTION
**Pull request by oliverbaehler**
Fix was successfully tested with this change. Now the question remains if the change is breaking. IMHO it is not but we can still talk about that.

FYI: i think the e2e is a bit broken. I will also try to fix it :)

closes #245

### CODE REVIEW

**Comment by oliverbaehler** [comment]
@prometherion any idea why the e2e is failinf? Should it even work .. ? :D

**Comment by prometherion** [comment]
The current e2e on bats is totally flaky and should be totally rewritten to Go.

May I ask you to test manually if everything's fine and no privilege escalation is possible?

**Review by prometherion — APPROVED** [review]
Honestly, LGTM but would be great to have a review along with some attempts in gaining privilege escalation.

**Comment by oliverbaehler** [comment]
Basic impersonation does not work:

```
╭─dev at dev-olb in ~/testing/capsule-proxy/hack on issue/245✘✘✘ 23-02-10 - 14:12:35
╰─⠠⠵ KUBECONFIG=alice.kubeconfig kubectl get ns            
NAME       STATUS   AGE
oil-dev    Active   1s
oil-test   Active   4s
╭─dev at dev-olb in ~/testing/capsule-proxy/hack on issue/245✘✘✘ 23-02-10 - 14:12:36
╰─⠠⠵ KUBECONFIG=alice.kubeconfig kubectl get ns --as bob
Error from server (Forbidden): cannot retrieve user and group: the current user alice cannot impersonate the user bob
╭─dev at dev-olb in ~/testing/capsule-proxy/hack on issue/245✘✘✘ 23-02-10 - 14:12:40
╰─⠠⠵ KUBECONFIG=alice.kubeconfig kubectl get ns --as bob --as some-group
Error from server (Forbidden): cannot retrieve user and group: the current user alice cannot impersonate the user some-group
╭─dev at dev-olb in ~/testing/capsule-proxy/hack on issue/245✘✘✘ 23-02-10 - 14:12:50
╰─⠠⠵ 
╭─dev at dev-olb in ~/testing/capsule-proxy/hack on issue/245✘✘✘ 23-02-10 - 14:13:02
╰─⠠⠵ KUBECONFIG=alice.kubeconfig kubectl get ns --as system:serviceaccount:capsule-system:default --as some-group
Error from server (Forbidden): cannot retrieve user and group: the current user alice cannot impersonate the user some-group
```

Allowed impersonation RBAC:

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: alice-impersonator
rules:
- apiGroups: [""]
  resources: ["users", "groups"]
  resourceNames: ["alice"]
  verbs: ["impersonate"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: alice-impersonator
subjects:
# You can specify more than one "subject"
- kind: User
  name: alice # "name" is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: ClusterRole #this must be Role or ClusterRole
  name: alice-impersonator # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io
```

Tried some impersonations:

```
╭─dev at dev-olb in ~/testing/capsule-proxy/hack on issue/245✘✘✘ 23-02-10 - 14:23:04
╰─⠠⠵ KUBECONFIG=alice.kubeconfig kubectl get ns --as alice --as alice --as-group allowed
NAME       STATUS   AGE
oil-dev    Active   10m
oil-test   Active   10m

╭─dev at dev-olb in ~/testing/capsule-proxy/hack on issue/245✘✘✘ 23-02-10 - 14:23:05
╰─⠠⠵ KUBECONFIG=alice.kubeconfig kubectl get ns --as alice --as alice
NAME       STATUS   AGE
oil-dev    Active   10m
oil-test   Active   10m

╭─dev at dev-olb in ~/testing/capsule-proxy/hack on issue/245✘✘✘ 23-02-10 - 14:23:10
╰─⠠⠵ KUBECONFIG=alice.kubeconfig kubectl get ns --as alice --as bob  
Error from server (Forbidden): cannot retrieve user and group: the current user alice cannot impersonate the user bob

╭─dev at dev-olb in ~/testing/capsule-proxy/hack on issue/245✘✘✘ 23-02-10 - 14:23:13
╰─⠠⠵ KUBECONFIG=alice.kubeconfig kubectl get ns --as alice --as alice --as-group allowed
NAME       STATUS   AGE
oil-dev    Active   10m
oil-test   Active   10m

╭─dev at dev-olb in ~/testing/capsule-proxy/hack on issue/245✘✘✘ 23-02-10 - 14:23:20
╰─⠠⠵ KUBECONFIG=alice.kubeconfig kubectl get ns --as alice --as alice --as-group alice  
NAME       STATUS   AGE
oil-dev    Active   10m
oil-test   Active   10m

╭─dev at dev-olb in ~/testing/capsule-proxy/hack on issue/245✘✘✘ 23-02-10 - 14:23:23
╰─⠠⠵ KUBECONFIG=alice.kubeconfig kubectl get ns --as alice --as alice --as-group some-group
Error from server (Forbidden): cannot retrieve user and group: the current user alice cannot impersonate the group some-group

╭─dev at dev-olb in ~/testing/capsule-proxy/hack on issue/245✘✘✘ 23-02-10 - 14:23:30
╰─⠠⠵ KUBECONFIG=alice.kubeconfig kubectl get ns --as alice --as alice --as-group system:masters          
Error from server (Forbidden): cannot retrieve user and group: the current user alice cannot impersonate the group system:masters

╭─dev at dev-olb in ~/testing/capsule-proxy/hack on issue/245✘✘✘ 23-02-10 - 14:24:09
╰─⠠⠵ KUBECONFIG=alice.kubeconfig kubectl get ns --as alice --as allowed --as-group system:masters
Error from server (Forbidden): cannot retrieve user and group: the current user alice cannot impersonate the group system:masters
```
Via cURL:

```
╭─dev at dev-olb in ~/testing/capsule-proxy/hack on issue/245✘✘✘ 23-02-10 - 14:29:32
╰─⠠⠵ curl  https://localhost:9010/api/v1/namespaces --cert alice-oil.crt --key alice-oil.key -H "Impersonate-User: bob"  
{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"cannot retrieve user and group: the current user alice cannot impersonate the user bob","reason":"Forbidden","code":403}%           

╭─dev at dev-olb in ~/testing/capsule-proxy/hack on issue/245✘✘✘ 23-02-10 - 14:29:34
╰─⠠⠵ curl  https://localhost:9010/api/v1/namespaces --cert alice-oil.crt --key alice-oil.key -H "Impersonate-User: alice" -H "Impersonate-Group: system:masters"
{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"cannot retrieve user and group: the current user alice cannot impersonate the group system:masters","reason":"Forbidden","code":403}

╭─dev at dev-olb in ~/testing/capsule-proxy/hack on issue/245✘✘✘ 23-02-10 - 14:30:03
╰─⠠⠵ curl  https://localhost:9010/api/v1/namespaces --cert alice-oil.crt --key alice-oil.key -H "Impersonate-User: alice" -H "Impersonate-Group: some-group"    
{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"cannot retrieve user and group: the current user alice cannot impersonate the group some-group","reason":"Forbidden","code":403}%  

╭─dev at dev-olb in ~/testing/capsule-proxy/hack on issue/245✘✘✘ 23-02-10 - 14:30:16
╰─⠠⠵ curl  https://localhost:9010/api/v1/namespaces --cert alice-oil.crt --key alice-oil.key -H "Impersonate-User: alice" -H "Impersonate-Group: allowed"  
-> Worked
```
To me it seems good. @prometherion anything else you would test? Should i directly bump to 0.3.3?

**Comment by prometherion** [comment]
Astonishing work, @oliverbaehler! 👏🏻 

We're already referring to the issue that is assigned to v0.3.3.

**Review by prometherion — APPROVED** [review]

**Pull request merged**
